# Generated by Django 4.1.2 on 2022-10-10 22:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Absent'), (1, 'Not Expected'), (2, 'Present')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'casual'), (1, 'vacation'), (2, 'medical'), (3, 'maternity'), (4, 'paternity'), (5, 'sabbatical'), (6, 'bereavement'), (7, 'other')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=512)),
                ('decision', models.IntegerField(choices=[(0, 'rejected'), (1, 'pending'), (2, 'approved')], default=0)),
                ('decision_date', models.DateField(null=True)),
            ],
        ),
    ]
